M48
; DRILL file {KiCad 7.0.2} date Wed Aug 23 16:26:37 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-08-23T16:26:37-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.270
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X168.96Y-76.5
X168.96Y-91.5
T2
X167.0Y-71.0
X167.0Y-121.0
X167.0Y-165.0
X225.0Y-84.5
X225.0Y-104.5
X227.0Y-71.0
X227.0Y-165.0
T3
X172.0Y-131.26
X172.0Y-155.0
X196.0Y-118.5
X217.4Y-158.2
T0
M30
